### ISSUE TITLE
udev blocking systemd

### ISSUE THREAD

**Issue by mkauzlar** [Sabayon/systemd-love#1]
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] app-admin/eselect-sysvinit-0.2::systemd-love  0 kB
[ebuild  N     ] app-admin/eselect-settingsd-0.1::systemd-love  0 kB
[ebuild     U  ] sys-apps/hwids-20130329 [20130302] USE="udev" 1,464 kB
[ebuild  N     ] sys-apps/systemd-200-r50::systemd-love  USE="acl cryptsetup gudev introspection kmod pam python tcpd -audit -doc -gcrypt -http -lzma -qrcode (-selinux) -static-libs -vanilla -xattr" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7" 2,061 kB
[blocks B      ] sys-fs/udev ("sys-fs/udev" is blocking sys-apps/systemd-200-r50)

Total: 4 packages (1 upgrade, 3 new), Size of downloads: 3,524 kB
Conflict: 1 block (1 unsatisfied)
- Error: The above package list contains packages which cannot be
- installed at the same time on the same system.
  
  (sys-apps/systemd-200-r50::systemd-love, ebuild scheduled for merge) pulled in by
    systemd
  
  (sys-fs/udev-197-r8::sabayon-distro, installed) pulled in by
    sys-fs/udev:0 required by @selected
  
  > =sys-fs/udev-096 required by (net-wireless/prism54-firmware-2.13::gentoo, installed)
  >   sys-fs/udev required by (sys-fs/zfs-userspace-20120903::sabayon-distro, installed)
  > =sys-fs/udev-197-r8[gudev,hwdb,introspection,keymap,kmod] required by (virtual/udev-197-r1::gentoo, installed)
  > =sys-fs/udev-096 required by (net-wireless/acx-firmware-20060207::gentoo, installed)
  > =sys-fs/udev-171[gudev] required by (net-misc/networkmanager-0.9.6.4::sabayon-distro, installed)
  > =sys-fs/udev-096 required by (net-wireless/prism54-firmware-1.0.4.3::gentoo, installed)

**Comment by lxnay** [comment]
You are supposed to replace sys-fs/udev with sys-apps/systemd. systemd contains udev.

**Comment by mkauzlar** [comment]
Can I just remove udev without conseguences?

equo rm  sys-fs/udev --pretend

> >  @@ These are the chosen packages:
> >    !!!  (1/1) sys-fs/udev-197-r8: vital package. Removal forbidden.
> >  @@ Packages involved: 1
> > Nothing to do

!!! 'sys-fs/udev' (virtual/dev-manager) is part of your system profile.
!!! Unmerging it may be damaging to your system.

 sys-fs/udev
    selected: 197-r8 
   protected: none 
     omitted: none

**Comment by lxnay** [comment]
Of course, just make sure to install systemd right after ;-)

**Comment by mkauzlar** [comment]
Then kmod pulls again udev and blocks... do I need to uninstall kmod as well?

alculating dependencies... done!
[ebuild     U  ] sys-apps/kmod-13 [12-r1] USE="lzma static-libs tools zlib -debug -doc" 1,403 kB
[ebuild  N     ] app-admin/eselect-sysvinit-0.2::systemd-love  0 kB
[ebuild  N     ] app-admin/eselect-settingsd-0.1::systemd-love  0 kB
[ebuild  N     ] sys-fs/udev-201  USE="acl firmware-loader gudev hwdb introspection keymap kmod openrc static-libs -doc (-selinux)" 2,081 kB
[ebuild     U  ] sys-fs/udev-init-scripts-25 [24] 5 kB
[ebuild     U  ] sys-apps/hwids-20130329 [20130302] USE="udev" 1,464 kB
[ebuild  N     ] sys-apps/systemd-200-r50::systemd-love  USE="acl cryptsetup gudev introspection kmod pam python tcpd -audit -doc -gcrypt -http -lzma -qrcode (-selinux) -static-libs -vanilla -xattr" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7" 2,061 kB
[blocks B      ] sys-fs/udev ("sys-fs/udev" is blocking sys-apps/systemd-200-r50)
[blocks B      ] sys-apps/systemd ("sys-apps/systemd" is blocking sys-fs/udev-201)
