### ISSUE TITLE
ZFS unit doesn't work in most cases

### ISSUE THREAD

**Issue by Rudd-O** [Sabayon/systemd-love#2]
It won't mount file systems that need to be mounted prior to local-fs.service (such as the root FS or others).  It will fail if files are open when this unit file is still active.

For better systemd support, look into https://github.com/Rudd-O/zfs

**Comment by lxnay** [comment]
Report it upstream then, not here.

**Comment by Rudd-O** [comment]
Oooookay.  Just remember that the service file you added here will cause problems for users.
