### ISSUE TITLE
sys-apps/sysvinit:  /bin/pidof moved to  sys-process/procps-3.3.9

### ISSUE THREAD

**Issue by geosone** [Sabayon/systemd-love#5]
pidof has moved to procps

**Comment by oleid** [comment]
this does the trick for me:

<pre>
--- sysvinit-2.88-r8.ebuild     2013-08-02 19:46:02.331188691 +0200
+++ sysvinit-2.88-r9.ebuild     2014-01-10 17:40:53.436336374 +0100
@@ -39,6 +39,8 @@
        # mountpoint/sulogin/utmpdump have moved to util-linux
        sed -i -r \
+              -e '/\/bin\/pidof/d' \
+              -e '/^MAN8/s:\<pidof.8\>::g' \
                -e '/^(USR)?S?BIN/s:\<(mountpoint|sulogin|utmpdump)\>::g' \
                -e '/^MAN[18]/s:\<(mountpoint|sulogin|utmpdump)[.][18]\>::g' \
</pre>

**Comment by lxnay** [comment]
What you want is to sync the ebuild in this overlay with the latest one in the portage tree.
